import * as vscode from 'vscode';
import type { MetadataPrefetchRefreshDetails } from '../metadata/prefetch';

/**
 * Small live diagnostics panel for the background metadata refresh. SQL is
 * generated by the extension's catalog providers; this panel never executes
 * or accepts SQL from the webview.
 */
export class MetadataRefreshDetailsPanel implements vscode.Disposable {
    private panel: vscode.WebviewPanel | undefined;
    private latest: readonly MetadataPrefetchRefreshDetails[] = [];

    update(details: readonly MetadataPrefetchRefreshDetails[]): void {
        this.latest = details;
        void this.panel?.webview.postMessage({ type: 'refresh-state', details: this.latest });
    }

    show(): void {
        if (!this.panel) {
            this.panel = vscode.window.createWebviewPanel(
                'netezza.metadataRefreshDetails',
                'Schema Refresh Details',
                { viewColumn: vscode.ViewColumn.Beside, preserveFocus: true },
                { enableScripts: true, retainContextWhenHidden: true },
            );
            this.panel.webview.html = getMetadataRefreshDetailsHtml();
            this.panel.onDidDispose(() => {
                this.panel = undefined;
            });
        }
        this.panel.reveal(vscode.ViewColumn.Beside, true);
        void this.panel.webview.postMessage({ type: 'refresh-state', details: this.latest });
    }

    dispose(): void {
        this.panel?.dispose();
        this.panel = undefined;
    }
}

function getMetadataRefreshDetailsHtml(): string {
    return /* html */ `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body { color: var(--vscode-foreground); background: var(--vscode-editor-background); font-family: var(--vscode-font-family); margin: 0; padding: 18px; }
  h1 { font-size: 1.25em; margin: 0 0 6px; }
  h2 { font-size: 1em; margin: 20px 0 8px; }
  .hint { color: var(--vscode-descriptionForeground); margin: 0 0 18px; }
  .controls { display: flex; flex-wrap: wrap; gap: 10px 16px; align-items: center; margin: 0 0 14px; }
  .controls label { display: flex; align-items: center; gap: 6px; }
  select { color: var(--vscode-dropdown-foreground); background: var(--vscode-dropdown-background); border: 1px solid var(--vscode-dropdown-border); padding: 3px 6px; }
  .refresh { border: 1px solid var(--vscode-panel-border); border-radius: 5px; padding: 12px; margin: 12px 0 22px; }
  .summary { display: flex; flex-wrap: wrap; gap: 8px 16px; align-items: baseline; }
  .connection { font-weight: 600; }
  .progress { color: var(--vscode-textLink-foreground); font-weight: 600; }
  .message { color: var(--vscode-descriptionForeground); width: 100%; }
  .query { border-left: 3px solid var(--vscode-panel-border); padding: 8px 10px; margin: 8px 0; background: var(--vscode-textCodeBlock-background); }
  .query.running { border-left-color: var(--vscode-testing-iconPassed); }
  .query.queued, .query.planned { border-left-color: var(--vscode-editorWarning-foreground); }
  .query.failed { border-left-color: var(--vscode-errorForeground); }
  .query.slow { border-left-color: var(--vscode-editorWarning-foreground); }
  .query.skipped { opacity: .68; }
  .meta { color: var(--vscode-descriptionForeground); font-size: .9em; }
  .state { font-weight: 600; text-transform: uppercase; margin-right: 8px; }
  pre { margin: 6px 0 0; white-space: pre-wrap; overflow-wrap: anywhere; font-family: var(--vscode-editor-font-family); font-size: .9em; }
  .error { color: var(--vscode-errorForeground); margin-top: 6px; }
  .empty { color: var(--vscode-descriptionForeground); font-style: italic; }
  .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(165px, 1fr)); gap: 8px; margin: 12px 0; }
  .stat { border: 1px solid var(--vscode-panel-border); border-radius: 4px; padding: 7px 9px; }
  .stat-label { color: var(--vscode-descriptionForeground); font-size: .85em; }
  .stat-value { display: block; margin-top: 3px; font-weight: 600; }
  .snapshot { color: var(--vscode-descriptionForeground); font-size: .9em; margin: 8px 0; }
  .snapshot.ok { color: var(--vscode-testing-iconPassed); }
  .snapshot.incomplete { color: var(--vscode-editorWarning-foreground); }
  .missing { margin: 6px 0 0 18px; padding: 0; font-family: var(--vscode-editor-font-family); font-size: .88em; }
</style>
</head>
<body>
<h1>Schema refresh diagnostics</h1>
<p class="hint">Executed, running, queued and planned catalog SQL. Planned statements may be skipped when a cache layer is already valid or when no external table exists.</p>
<div class="controls">
  <label>Status <select id="status-filter"><option value="all">All</option><option value="running">Running</option><option value="failed">Failed</option><option value="timeout">Timeout</option><option value="slow">Slow (&gt; 5 s)</option><option value="completed">Completed</option><option value="queued">Queued</option><option value="planned">Planned</option><option value="skipped">Skipped</option></select></label>
  <label>Sort <select id="sort-order"><option value="duration-desc">Execution time (longest first)</option><option value="started-desc">Started most recently</option><option value="queue-desc">Queue wait (longest first)</option><option value="duration-asc">Execution time (shortest first)</option></select></label>
</div>
<main id="content"><p class="empty">No schema refresh has started in this VS Code session.</p></main>
<script>
  const content = document.getElementById('content');
  const statusFilter = document.getElementById('status-filter');
  const sortOrder = document.getElementById('sort-order');
  const slowQueryThresholdMs = 5000;
  let currentDetails = [];
  const labels = {
    running: 'Running now', queued: 'Queued', planned: 'Planned next',
    completed: 'Executed', failed: 'Failed', skipped: 'Skipped'
  };
  const stateLabel = {
    running: 'running', queued: 'queued', planned: 'planned',
    completed: 'completed', failed: 'failed', skipped: 'skipped'
  };
  const escapeHtml = (value) => String(value || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
  const formatTime = (timestamp) => timestamp ? new Date(timestamp).toLocaleTimeString() : '';
  const durationMs = (query, now) => query.startedAt ? (query.completedAt || now) - query.startedAt : 0;
  const formatDuration = (milliseconds) => milliseconds >= 1000
    ? (milliseconds / 1000).toFixed(milliseconds >= 10000 ? 1 : 2) + ' s'
    : milliseconds + ' ms';
  const isSlow = (query, now) => durationMs(query, now) > slowQueryThresholdMs;
  const isTimeout = (query) => /timeout|timed out/i.test(query.error || '');
  const formatQuery = (query) => {
    const now = Date.now();
    const duration = query.startedAt ? ' · ' + formatDuration(durationMs(query, now)) : '';
    const queue = query.queueWaitMs ? ' · queue ' + query.queueWaitMs + ' ms' : '';
    const rows = typeof query.rowsRead === 'number' ? ' · ' + query.rowsRead + ' rows' : '';
    const target = [query.context.database, query.context.schema, query.context.table].filter(Boolean).join('.') || 'connection scope';
    const slow = isSlow(query, now) ? ' slow' : '';
    return '<article class="query ' + escapeHtml(query.state) + slow + '">'
      + '<div><span class="state">' + escapeHtml(stateLabel[query.state] || query.state) + '</span>'
      + '<span class="meta">' + escapeHtml(query.context.kind || 'catalog') + ' · ' + escapeHtml(target) + duration + queue + rows + '</span></div>'
      + '<pre>' + escapeHtml(query.sql) + '</pre>'
      + (query.error ? '<div class="error">' + escapeHtml(query.error) + '</div>' : '')
      + '</article>';
  };
  const getFilteredSortedQueries = (queries) => {
    const now = Date.now();
    const status = statusFilter.value;
    const filtered = queries.filter(query => status === 'all'
      || (status === 'slow' ? isSlow(query, now) : status === 'timeout' ? isTimeout(query) : query.state === status));
    return filtered.sort((left, right) => {
      if (sortOrder.value === 'duration-asc') return durationMs(left, now) - durationMs(right, now);
      if (sortOrder.value === 'started-desc') return (right.startedAt || right.queuedAt) - (left.startedAt || left.queuedAt);
      if (sortOrder.value === 'queue-desc') return (right.queueWaitMs || 0) - (left.queueWaitMs || 0);
      return durationMs(right, now) - durationMs(left, now);
    });
  };
  const renderGroup = (queries, state) => {
    const entries = queries.filter(query => query.state === state);
    return entries.length ? '<h2>' + labels[state] + ' (' + entries.length + ')</h2>' + entries.map(formatQuery).join('') : '';
  };
  const renderSnapshot = (snapshot) => {
    if (!snapshot) return '';
    if (snapshot.complete) return '<div class="snapshot ok">Snapshot complete: all prefetched object layers have columns.</div>';
    const parts = [];
    if (snapshot.missingStages && snapshot.missingStages.length) parts.push('missing stages: ' + snapshot.missingStages.join(', '));
    if (snapshot.missingColumnCount) parts.push('missing column layers: ' + snapshot.missingColumnCount);
    const examples = (snapshot.missingColumnKeys || []).map(key => '<li>' + escapeHtml(key) + '</li>').join('');
    return '<div class="snapshot incomplete">Snapshot incomplete' + (parts.length ? ' — ' + escapeHtml(parts.join('; ')) : '') + '</div>'
      + (examples ? '<ul class="missing">' + examples + '</ul>' : '');
  };
  const renderStats = (refresh, queries) => {
    const now = Date.now();
    const objectQueries = queries.filter(query => query.context.kind === 'objects' || query.context.kind === 'external-objects');
    const columnQueries = queries.filter(query => query.context.kind === 'columns' || query.context.kind === 'external-columns');
    const objectRows = objectQueries.reduce((total, query) => total + (query.rowsRead || 0), 0);
    const columnRows = columnQueries.reduce((total, query) => total + (query.rowsRead || 0), 0);
    const objectDuration = objectQueries.reduce((total, query) => total + durationMs(query, now), 0);
    const columnDuration = columnQueries.reduce((total, query) => total + durationMs(query, now), 0);
    const timed = queries.filter(query => query.startedAt);
    const slowest = timed.reduce((current, query) => !current || durationMs(query, now) > durationMs(current, now) ? query : current, undefined);
    const slowestValue = slowest
      ? formatDuration(durationMs(slowest, now)) + ' · ' + (slowest.context.kind || 'catalog')
      : '—';
    const values = [
      ['Tables / views', objectRows + ' rows · ' + formatDuration(objectDuration)],
      ['Columns', columnRows + ' rows · ' + formatDuration(columnDuration)],
      ['Refresh elapsed', formatDuration(now - refresh.startedAt)],
      ['Longest single SQL', slowestValue],
    ];
    return '<div class="stats">' + values.map(value => '<div class="stat"><span class="stat-label">' + value[0] + '</span><span class="stat-value">' + escapeHtml(value[1]) + '</span></div>').join('') + '</div>';
  };
  const render = (details) => {
    if (!details || details.length === 0) {
      content.innerHTML = '<p class="empty">No schema refresh has started in this VS Code session.</p>';
      return;
    }
    content.innerHTML = details.map(refresh => {
      const allQueries = [...refresh.queries];
      const queries = getFilteredSortedQueries(allQueries);
      return '<section class="refresh">'
        + '<div class="summary"><span class="connection">' + escapeHtml(refresh.connectionName) + '</span>'
        + '<span class="progress">' + escapeHtml(refresh.percent) + '%</span>'
        + '<span class="meta">' + escapeHtml(refresh.stage) + ' · updated ' + escapeHtml(formatTime(refresh.updatedAt)) + '</span>'
        + '<span class="message">' + escapeHtml(refresh.message) + '</span></div>'
        + renderStats(refresh, allQueries)
        + renderSnapshot(refresh.snapshot)
        + renderGroup(queries, 'running')
        + renderGroup(queries, 'queued')
        + renderGroup(queries, 'planned')
        + renderGroup(queries, 'failed')
        + renderGroup(queries, 'completed')
        + renderGroup(queries, 'skipped')
        + '</section>';
    }).join('');
  };
  statusFilter.addEventListener('change', () => render(currentDetails));
  sortOrder.addEventListener('change', () => render(currentDetails));
  setInterval(() => render(currentDetails), 1000);
  window.addEventListener('message', event => {
    if (event.data && event.data.type === 'refresh-state') {
      currentDetails = event.data.details || [];
      render(currentDetails);
    }
  });
</script>
</body>
</html>`;
}
