import type { SchemaTreeNode } from '@justybase/contracts';
import type { WorkspaceStorage } from './workspacePersistence';

export interface SharedSchemaShortcuts {
  readonly favorites: readonly SchemaTreeNode[];
  readonly recent: readonly SchemaTreeNode[];
}

const MAX_FAVORITES = 20;
const MAX_RECENT = 8;

export function sharedSchemaStorageKey(connectionId: string): string {
  return `schema_${connectionId}`;
}

/**
 * IDs are generated by the metadata service and may change after a refresh.
 * Catalog identity keeps shortcuts valid across metadata reloads.
 */
export function sharedSchemaObjectIdentity(node: SchemaTreeNode): string {
  return [node.kind, node.database ?? '', node.schema ?? '', node.objectName ?? node.label].join('\u001f');
}

function isObjectNode(value: unknown): value is SchemaTreeNode {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Partial<SchemaTreeNode>;
  return candidate.kind === 'object'
    && typeof candidate.id === 'string'
    && typeof candidate.label === 'string'
    && typeof candidate.hasChildren === 'boolean';
}

function persistableNode(node: SchemaTreeNode): SchemaTreeNode {
  return {
    id: node.id,
    kind: 'object',
    label: node.label,
    database: node.database,
    schema: node.schema,
    objectName: node.objectName,
    objectType: node.objectType,
    hasChildren: node.hasChildren,
  };
}

function readStoredValue(storage: WorkspaceStorage, connectionId: string, legacyValue?: string | null): SharedSchemaShortcuts {
  try {
    const raw = storage.get(sharedSchemaStorageKey(connectionId)) ?? legacyValue;
    if (!raw) return { favorites: [], recent: [] };
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== 'object' || parsed === null) return { favorites: [], recent: [] };
    const value = parsed as { readonly favorites?: unknown; readonly recent?: unknown };
    return {
      favorites: Array.isArray(value.favorites) ? value.favorites.filter(isObjectNode).map(persistableNode).slice(0, MAX_FAVORITES) : [],
      recent: Array.isArray(value.recent) ? value.recent.filter(isObjectNode).map(persistableNode).slice(0, MAX_RECENT) : [],
    };
  } catch {
    return { favorites: [], recent: [] };
  }
}

export function readSharedSchemaShortcuts(storage: WorkspaceStorage, connectionId: string, legacyValue?: string | null): SharedSchemaShortcuts {
  return readStoredValue(storage, connectionId, legacyValue);
}

export function writeSharedSchemaShortcuts(storage: WorkspaceStorage, connectionId: string, shortcuts: SharedSchemaShortcuts): void {
  try {
    storage.set(sharedSchemaStorageKey(connectionId), JSON.stringify({
      favorites: shortcuts.favorites.filter(node => node.kind === 'object').map(persistableNode).slice(0, MAX_FAVORITES),
      recent: shortcuts.recent.filter(node => node.kind === 'object').map(persistableNode).slice(0, MAX_RECENT),
    }));
  } catch {
    // WorkspaceStorage intentionally treats browser storage as optional.
  }
}

export function rememberSharedSchemaObject(recent: readonly SchemaTreeNode[], node: SchemaTreeNode): readonly SchemaTreeNode[] {
  if (node.kind !== 'object') return recent;
  const identity = sharedSchemaObjectIdentity(node);
  return [persistableNode(node), ...recent.filter(item => sharedSchemaObjectIdentity(item) !== identity)].slice(0, MAX_RECENT);
}

export function toggleSharedSchemaFavorite(favorites: readonly SchemaTreeNode[], node: SchemaTreeNode): readonly SchemaTreeNode[] {
  if (node.kind !== 'object') return favorites;
  const identity = sharedSchemaObjectIdentity(node);
  if (favorites.some(item => sharedSchemaObjectIdentity(item) === identity)) {
    return favorites.filter(item => sharedSchemaObjectIdentity(item) !== identity);
  }
  return [persistableNode(node), ...favorites].slice(0, MAX_FAVORITES);
}
