export type { DatabaseKind, DatabaseCapabilities, DatabaseDialect, DatabaseSqlAuthoring } from './database';
export { DEFAULT_DATABASE_KIND, DATABASE_KIND_DISPLAY_NAMES, SUPPORTED_DATABASE_KINDS, createDatabaseCapabilities, createDatabaseDialectTraits } from './database';
export type { DatabaseConnection, DatabaseCommand, DatabaseDataReader } from './database';
export type { DatabaseConnectionConfig, DatabaseConnectionConstructor, DatabaseConnectionStaticConstructor } from './database';
export type { DatabaseConnectionFormSchema, DatabaseConnectionOptions, DatabaseConnectionFieldSchema, DatabaseConnectionFieldType, DatabaseConnectionFieldOption, DatabaseConnectionOptionValue } from './database';
export type { DatabaseMetadataProvider, DatabaseColumnQueryOptions, DatabaseColumnLookupParams, DatabaseMirroredSystemCatalog, DatabaseSourceSearchQueryOptions } from './database';
export type { DatabaseDialectTraits, DatabaseIdentifierTraits, DatabaseQualificationTraits, DatabaseCompletionTraits, DatabaseObjectSupportTraits, DatabaseDialectTraitsOverrides, DatabaseThreePartNamePrefix } from './database';

export type { DatabaseAdvancedFeatures, DatabaseDdlProvider, DatabaseDdlColumnInfo, DatabaseDdlKeyInfo, DatabaseDdlResult, DatabaseProcedureInfo, DatabaseExternalTableInfo, DatabaseBatchDDLOptions, DatabaseBatchDDLResult, DatabaseImportDataType, DatabaseColumnTypeChooser, DatabaseImportTypeMapper, DatabaseTuningAdvisor, DatabaseTuningAdvisorInput, DatabaseMaintenanceProvider, DatabaseMaintenanceTarget, DatabaseMaintenanceServices, DatabasePartitionInfo, DatabaseCreatePartitionOptions, DatabaseAttachPartitionOptions, DatabaseIndexInfo, DatabaseCreateIndexOptions, DatabaseSessionMonitorProvider, DatabaseCopilotReferenceProvider, DatabaseReferenceTopic } from './database';

export type { ConnectionDetails, NamedConnectionDetails } from './connectionDetails';

export type { TuningReport, TuningRecommendation, TuningEvidence, TuningSeverity, TuningRisk, TuningEvidenceSource, TuningReportMetadata } from './tuning/types';
export { clampConfidence, buildTuningSummary, createTuningReport } from './tuning/types';

export type {
  ApiError,
  AdminUserCreateRequest,
  AdminUserSummary,
  AdminUserUpdateRequest,
  AdminRestoreRequest,
  AdminRestoreResponse,
  AuthResponse,
  ConnectionProfileInput,
  ConnectionProfileUpdate,
  ConnectionProfileSummary,
  HistoryEntry,
  MetadataColumn,
  MetadataDatabase,
  MetadataObject,
  MetadataSchema,
  EditorPreferences,
  EditorPreferencesPatch,
  QueryColumnFilterSpec,
  QueryPageRequest,
  QueryPageResponse,
  QueryAggregateFunction,
  QueryAggregateRequest,
  QueryAggregateResponse,
  QueryAggregateValue,
  QueryGroupAggregate,
  QueryGroupRequest,
  QueryGroupResponse,
  QueryAuditEntry,
  QueryAuditStatus,
  QueryEditPreviewRequest,
  QueryEditRequest,
  QueryImportPreviewRequest,
  QueryImportRequest,
  QueryFileImportFormat,
  QueryFileImportPreviewRequest,
  QueryFileImportRequest,
  QueryProgressEvent,
  QuerySessionEvent,
  QuerySortSpec,
  QueryExportFormat,
  QueryExportRequest,
  SchemaNodeKind,
  SchemaSearchRequest,
  SchemaSearchResponse,
  SchemaSearchResult,
  SchemaTreeNode,
  SchemaTreeResponse,
  QueryCancelledEvent,
  QueryBatchCompleteEvent,
  QueryColumnsEvent,
  QueryColumn,
  QueryCompleteEvent,
  QueryErrorEvent,
  QueryEvent,
  QueryEventBase,
  QueryRowsEvent,
  QueryStartRequest,
  QueryStartResponse,
  QueryPreviewResponse,
  QueryPreviewStatement,
  QueryWriteResponse,
  TableWriteTarget,
  WriteOperationPreviewResponse,
  QueryStartedEvent,
  QueryStatementStartedEvent,
  QueryExecutionMode,
  SqlCompletionItem,
  SqlCompletionRequest,
  SqlCompletionResponse,
  SqlDiagnostic,
  SqlDiagnosticsRequest,
  SqlDiagnosticsResponse,
  SqlDiagnosticPosition,
  SqlFormatRequest,
  SqlFormatResponse,
  SqlLanguageContext,
  WebUser,
} from './webApi';
