export type { DatabaseKind, DatabaseCapabilities, DatabaseDialect, DatabaseSqlAuthoring, DatabaseSqlFunctionSignature, DatabaseSqlValidationProfile, DatabaseSqlTypeSpec, DatabaseSqlLintIssue, DatabaseSqlQualityRule, DatabaseSqlFormatterProfile, DatabaseSqlParsingProfile, DatabaseSqlStaticAssetProfile } from './database';
export { DEFAULT_DATABASE_KIND, DATABASE_KIND_DISPLAY_NAMES, SUPPORTED_DATABASE_KINDS, createDatabaseCapabilities, createDatabaseDialectTraits, normalizeDatabaseKind, tryNormalizeDatabaseKind } from './database';
export type { DatabaseConnection, DatabaseCommand, DatabaseDataReader } from './database';
export type { DatabaseConnectionConfig, DatabaseConnectionConstructor, DatabaseConnectionStaticConstructor } from './database';
export type { DatabaseConnectionFormSchema, DatabaseConnectionOptions, DatabaseConnectionFieldSchema, DatabaseConnectionFieldType, DatabaseConnectionFieldOption, DatabaseConnectionOptionValue } from './database';
export type { DatabaseMetadataProvider, DatabaseColumnQueryOptions, DatabaseColumnsWithKeysQuerySet, DatabaseColumnLookupParams, DatabaseMirroredSystemCatalog, DatabaseSourceSearchQueryOptions } from './database';
export type { DatabaseDialectTraits, DatabaseIdentifierTraits, DatabaseQualificationTraits, DatabaseCompletionTraits, DatabaseObjectSupportTraits, DatabaseDialectTraitsOverrides, DatabaseThreePartNamePrefix } from './database';
export type { DatabaseDesignerCapabilities, DatabaseDesignerCapability, DatabaseDesignerCapabilityKey, DatabaseDesignerColumn, DatabaseDesignerConstraint, DatabaseDesignerDefinition, DatabaseDesignerDiagnostic, DatabaseDesignerIndex, DatabaseDesignerNativeDefinition, DatabaseDesignerPartition, DatabaseDesignerProvider, DatabaseDesignerRelationalIndex, DatabaseDesignerRequirement, DatabaseDesignerRuntimeContext, DatabaseDesignerTarget, DatabaseDesignerTrigger, DatabaseDesignerTriggerCapability, DatabaseDesignerViewCapability, DatabaseDesignerRoutineCapability, DatabaseObjectSnapshot, DatabaseSchemaChangePlan, DatabaseSchemaChangeStatement, DatabaseViewDesignerDefinition, DatabaseTableDesignerDefinition, DesignerCapabilityReasonCode, DesignerNativeFeature, DesignerOperation, DesignerSupportLevel, DesignerRoutineBodyStyle, DesignerTriggerBodyStyle, DesignerTriggerEvent, DesignerTriggerLevel, DesignerTriggerTiming, DesignerViewReplaceStyle } from './database';
export { UnsupportedDesignerOperationError } from './database';
export { DATABASE_DESIGNER_CAPABILITY_MANIFESTS, DESIGNER_CAPABILITY_KEYS, DESIGNER_OPERATIONS, getDatabaseDesignerCapabilities, getDesignerCapability, resolveDatabaseDesignerCapabilities } from './database';
export type * from './webviews';

export type { DatabaseAdvancedFeatures, DatabaseDdlProvider, DatabaseDdlColumnInfo, DatabaseDdlKeyInfo, DatabaseTableDdlMetadata, DatabaseDdlResult, DatabaseTableDefinitionMetadata, DatabaseProcedureInfo, DatabaseExternalTableInfo, DatabaseBatchDDLOptions, DatabaseBatchDDLResult, DatabaseImportDataType, DatabaseColumnTypeChooser, DatabaseImportTypeMapper, DatabaseTuningAdvisor, DatabaseTuningAdvisorInput, DatabaseMaintenanceProvider, DatabaseMaintenanceTarget, DatabaseMaintenanceServices, DatabaseRecreateTableResult, DatabasePartitionInfo, DatabaseCreatePartitionOptions, DatabaseAttachPartitionOptions, DatabaseIndexInfo, DatabaseCreateIndexOptions, DatabaseSessionMonitorServices, DatabaseSessionMonitorProvider, DatabaseCopilotReferenceProvider, DatabaseReferenceTopic, DatabaseExplainOptions, DatabaseExplainProvider, DatabaseQueryProfileProvider, DatabaseStageLocation, DatabaseInlineFileFormatOptions, DatabaseCopyIntoTableOptions, DatabaseCopyIntoStageOptions, DatabaseStageWorkflowProvider, DatabaseImportWizardInput, DatabaseImportExecutionPlan, DatabaseImportWizardProvider } from './database';

export type { ConnectionDetails, DatabaseTunnelConfig, NamedConnectionDetails } from './connectionDetails';
export {
  UI_CONTRACT_VERSION,
  isCapabilityDescriptor,
  isUiAuthState,
  isUiCapabilitySnapshot,
  isRedactedConnectionProfile,
} from './ui';
export type {
  CapabilityDescriptor,
  CapabilityStatus,
  ElectronRendererApi,
  OpaqueCredentialRequestId,
  UiConnectionProfileInput,
  PersistenceEnvelope,
  PersistenceScope,
  RedactedConnectionProfile,
  UiAuthState,
  UiCapabilitySnapshot,
  UiIdentity,
  UiMode,
  UiOperationState,
  UiOperationStatus,
  UiPreloadAuthRequest,
  UiPreloadCapabilitiesRequest,
  UiPreloadConnectionsRequest,
  UiPreloadCredentialRequest,
  UiPreloadRequest,
  UiPreloadResponse,
  UiRendererBootstrap,
} from './ui';
export { isUiConnectionProfileInput } from './ui';
export type {
  ConnectionQueryResult,
  ConnectionSummary,
  JustyBaseLiteApi,
  OpenFileSqlSessionOptions,
  OpenFileSqlWorkspaceSessionOptions,
  SavedConnectionSummary,
} from './companionApi';

export type {
  ImportColumnOptions,
  ImportColumnDescriptor,
  ProgressCallback,
  SnowflakeWorkflowDetails,
  ImportResultDetails,
  ImportResult,
} from './import';

export type {
  Awaitable,
  DatabaseQueryCallbacks,
  DatabaseQueryCommand,
  DatabaseQueryOptions,
  DatabaseQueryResult,
  ExecutionBatchCompletedEvent,
  ExecutionColumnsEvent,
  ExecutionConnectionMode,
  ExecutionContext,
  ExecutionDelivery,
  ExecutionEvent,
  ExecutionFailure,
  ExecutionPhase,
  ExecutionProgressEvent,
  ExecutionRequest,
  ExecutionRetryPolicy,
  ExecutionRetryingEvent,
  ExecutionRetryingEventEnvelope,
  ExecutionRowsEvent,
  ExecutionStartedEvent,
  ExecutionStatement,
  ExecutionStatementCompletedEvent,
  ExecutionStatementFailedEvent,
  ExecutionStatementStartedEvent,
  ExecutionStatementSummary,
  ExecutionSummary,
  ExecutionTerminalStatus,
  ExecutionTerminalEvent,
} from './queryExecution';

export type { TuningReport, TuningRecommendation, TuningEvidence, TuningSeverity, TuningRisk, TuningEvidenceSource, TuningReportMetadata } from './tuning/types';
export { clampConfidence, buildTuningSummary, createTuningReport } from './tuning/types';

export type {
  ApiError,
  AdminUserCreateRequest,
  AdminUserSummary,
  AdminUserUpdateRequest,
  AdminRestoreRequest,
  AdminRestoreResponse,
  AuthResponse,
  ConnectionProfileInput,
  ConnectionProfileUpdate,
  ConnectionProfileSummary,
  HistoryEntry,
  MetadataColumn,
  MetadataDdlRequest,
  MetadataDdlResponse,
  MetadataDatabase,
  MetadataObject,
  MetadataSchema,
  DesignerCapabilitiesRequest,
  DesignerCapabilitiesResponse,
  DesignerChangeContext,
  DesignerSnapshotRequest,
  DesignerSnapshotResponse,
  EditorPreferences,
  EditorPreferencesPatch,
  QueryColumnFilterSpec,
  QueryPageRequest,
  QueryPageResponse,
  QueryAggregateFunction,
  QueryAggregateRequest,
  QueryAggregateResponse,
  QueryAggregateValue,
  QueryGroupAggregate,
  QueryGroupRequest,
  QueryGroupResponse,
  QueryAuditEntry,
  QueryAuditStatus,
  QueryEditPreviewRequest,
  QueryEditRequest,
  QueryImportPreviewRequest,
  QueryImportRequest,
  QueryFileImportFormat,
  QueryFileImportPreviewRequest,
  QueryFileImportRequest,
  QueryProgressEvent,
  QuerySessionEvent,
  QuerySortSpec,
  QueryExportFormat,
  QueryExportRequest,
  SchemaNodeKind,
  SchemaSearchRequest,
  SchemaSearchResponse,
  SchemaSearchResult,
  SchemaTreeNode,
  SchemaTreeResponse,
  QueryCancelledEvent,
  QueryBatchCompleteEvent,
  QueryColumnsEvent,
  QueryColumn,
  QueryCompleteEvent,
  QueryErrorEvent,
  QueryEvent,
  QueryEventBase,
  QueryRowsEvent,
  QueryStartRequest,
  QueryStartResponse,
  QueryPreviewResponse,
  QueryPreviewStatement,
  QueryWriteResponse,
  TableWriteTarget,
  WriteOperationPreviewResponse,
  QueryStartedEvent,
  QueryStatementStartedEvent,
  QueryExecutionMode,
  SqlCompletionItem,
  SqlCompletionRequest,
  SqlCompletionResponse,
  SqlDiagnostic,
  SqlDiagnosticsRequest,
  SqlDiagnosticsResponse,
  SqlDiagnosticPosition,
  SqlFormatRequest,
  SqlFormatResponse,
  SqlLanguageContext,
  WebUser,
} from './webApi';
