module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  preset: 'ts-jest',
  testMatch: ['<rootDir>/tests/**/*.test.ts', '<rootDir>/tests/**/*.test.tsx'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  moduleNameMapper: {
    '^.+\\.css$': '<rootDir>/tests/styleStub.cjs',
    '^@justybase/api-client$': '<rootDir>/../../packages/api-client/src',
    '^@justybase/api-client/(.*)$': '<rootDir>/../../packages/api-client/src/$1',
    '^@justybase/contracts$': '<rootDir>/../../packages/contracts/src',
    '^@justybase/dialect-utils$': '<rootDir>/../../packages/dialect-utils/src',
    '^@justybase/dialect-utils/(.*)$': '<rootDir>/../../packages/dialect-utils/src/$1',
    '^@justybase/sql-core$': '<rootDir>/../../packages/sql-core/src/index.ts',
    '^@justybase/sql-core/(.*)$': '<rootDir>/../../packages/sql-core/src/$1',
    '^@justybase/ui-core$': '<rootDir>/../../packages/ui-core/src',
    '^@justybase/ui-monaco$': '<rootDir>/../../packages/ui-monaco/src',
    '^@justybase/ui-react$': '<rootDir>/../../packages/ui-react/src',
    '^@chevrotain/(.+)$': '<rootDir>/../../node_modules/@chevrotain/$1/lib/src/api.js',
  },
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { tsconfig: 'tsconfig.json' }],
    '^.+\\.[mc]?js$': ['babel-jest', {
      presets: [['@babel/preset-env', { targets: { node: 'current' }, modules: 'commonjs' }]],
    }],
  },
  transformIgnorePatterns: ['/node_modules/(?!chevrotain|@chevrotain)/'],
  collectCoverageFrom: ['src/**/*.ts', 'src/**/*.tsx', '!src/**/*.d.ts'],
  coverageDirectory: 'coverage',
  coverageReporters: ['text-summary', 'json-summary', 'lcov'],
};
