import {
  BASE_SQL_BUILTIN_FUNCTIONS,
  BASE_SQL_SPECIAL_BUILTIN_VALUES,
  mergeStringSets,
} from '../../../sql/authoring/baseProfiles';

export const DUCKDB_BUILTIN_FUNCTIONS = mergeStringSets(
  BASE_SQL_BUILTIN_FUNCTIONS,
  new Set([
    'APPROX_COUNT_DISTINCT',
    'ARG_MAX',
    'ARG_MIN',
    'ARRAY_AGG',
    'ARRAY_CONCAT',
    'ARRAY_EXTRACT',
    'ARRAY_LENGTH',
    'ARRAY_SLICE',
    'CONCAT_WS',
    'DATE_PART',
    'DATE_TRUNC',
    'EPOCH',
    'EPOCH_MS',
    'FIRST',
    'GENERATE_SERIES',
    'HISTOGRAM',
    'LAST',
    'LIST',
    'LIST_AGGREGATE',
    'LIST_EXTRACT',
    'LIST_FILTER',
    'LIST_REVERSE_SORT',
    'LIST_SORT',
    'LIST_VALUE',
    'MAP',
    'MAP_EXTRACT',
    'QUANTILE',
    'QUANTILE_CONT',
    'QUANTILE_DISC',
    'READ_AVRO',
    'READ_CSV',
    'READ_CSV_AUTO',
    'READ_JSON',
    'READ_JSON_AUTO',
    'READ_PARQUET',
    'READ_XLSX',
    'REGEXP_EXTRACT',
    'REGEXP_EXTRACT_ALL',
    'REGEXP_REPLACE',
    'REGEXP_SPLIT_TO_ARRAY',
    'ROUND_EVEN',
    'STRFTIME',
    'STRPTIME',
    'STRUCT_EXTRACT',
    'STRUCT_PACK',
    'UNNEST',
    'UUID',
  ]),
);

export const DUCKDB_SPECIAL_BUILTIN_VALUES = mergeStringSets(
  BASE_SQL_SPECIAL_BUILTIN_VALUES,
  new Set([
    'CURRENT_DATE',
    'CURRENT_LOCALTIME',
    'CURRENT_LOCALTIMESTAMP',
    'CURRENT_TIME',
    'CURRENT_TIMESTAMP',
    'CURRENT_USER',
    'FALSE',
    'NULL',
    'TRUE',
  ]),
);

export const DUCKDB_SYSTEM_COLUMNS = new Set<string>();
