import {
  BASE_SQL_COMPLETION_KEYWORDS,
  BASE_SQL_FORMATTER_PROFILE,
  extendFormatterProfile,
  mergeUniqueStrings,
} from '../../../sql/authoring/baseProfiles';
import type { DatabaseSqlFormatterProfile } from '../../../sql/authoring/types';

export const DUCKDB_COMPLETION_KEYWORDS = mergeUniqueStrings(
  BASE_SQL_COMPLETION_KEYWORDS,
  [
    'ASOF JOIN',
    'ANTI JOIN',
    'ATTACH',
    'COLUMNS',
    'CREATE MACRO',
    'CREATE FUNCTION',
    'CREATE TYPE',
    'DETACH',
    'EXCLUDE',
    'INCLUDE NULLS',
    'INSTALL',
    'LATERAL',
    'LOAD',
    'MACRO',
    'PIVOT',
    'PIVOT_LONGER',
    'PIVOT_WIDER',
    'POSITIONAL JOIN',
    'PERCENT',
    'QUALIFY',
    'READ_AVRO',
    'READ_CSV',
    'READ_CSV_AUTO',
    'READ_JSON',
    'READ_PARQUET',
    'REPLACE',
    'RENAME',
    'REPEATABLE',
    'SAMPLE',
    'SEMI JOIN',
    'TABLESAMPLE',
    'UNPIVOT',
    'USING SAMPLE',
    'USE',
    'WITH ORDINALITY',
    'WINDOW',
  ],
);

export const duckdbFormatterProfile: DatabaseSqlFormatterProfile = extendFormatterProfile(
  BASE_SQL_FORMATTER_PROFILE,
  {
    keywords: [
      'ASOF',
      'ANTI',
      'ATTACH',
      'FUNCTION',
      'DETACH',
      'EXCLUDE',
      'INCLUDE',
      'INSTALL',
      'LATERAL',
      'LOAD',
      'PIVOT',
      'PIVOT_LONGER',
      'PIVOT_WIDER',
      'QUALIFY',
      'REPLACE',
      'RENAME',
      'REPEATABLE',
      'SAMPLE',
      'SEMI',
      'TABLESAMPLE',
      'UNPIVOT',
      'USE',
      'WINDOW',
    ],
    clauseKeywords: ['GROUP BY', 'HAVING', 'QUALIFY', 'ORDER BY', 'LIMIT', 'OFFSET', 'USING SAMPLE'],
    newlineBeforeKeywords: ['GROUP BY', 'HAVING', 'QUALIFY', 'ORDER BY', 'LIMIT', 'OFFSET', 'USING SAMPLE'],
    joinModifiers: ['ASOF', 'POSITIONAL'],
  },
);
